# Generated by Django 6.0.3 on 2026-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='cost_type',
            field=models.CharField(choices=[('reward_points', 'Reward Points'), ('cuti_points', 'Cuti Points')], default='reward_points', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='expected_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='reward_points',
            field=models.IntegerField(default=1),
        ),
    ]
