# Generated by Django 6.0.3 on 2026-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_globalsettings_todo_description_alter_todo_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cost', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cuti_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='last_reset_month',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='leaves_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='monthly_leaves_quota',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='next_month_leaves_quota',
            field=models.IntegerField(default=3),
        ),
    ]
