# Generated by Django 6.0.3 on 2026-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_globalsettings_reward_points_rewarditem_cost_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewarditem',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='rewarditem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='rewarditem',
            name='cost_type',
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='cost_cuti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='cost_rp',
            field=models.IntegerField(default=0),
        ),
    ]
