# Generated by Django 6.0.3 on 2026-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rewarditem_globalsettings_cuti_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='size',
            field=models.CharField(choices=[('cuti', 'Cuti'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='urgency',
            field=models.CharField(choices=[('cuti', 'Cuti'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
